8 -> main
gazebosim/gz-fuel-tools pull request #327
Opened 2023-02-14 00:52 UTC by iche033

# ➡️ Forward port

Port gz-fuel_tools8 to main

Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...merge_8_main_02132023

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

2023-02-14 08:49 UTC, ahcorde requested changes
MacOS is not able to compile and I can see many tests failing on windows, is this expected?

```bash
    gz-msgs10Config.cmake
    gz-msgs10-config.cmake
```

2023-02-14 18:50 UTC, iche033 commented
mac homebrew CI probably needs https://github.com/osrf/homebrew-simulation/pull/2203 to be merged first

windows test failures are expected. I've seen those fail before

2023-02-15 00:07 UTC, iche033 commented
> mac homebrew CI probably needs https://github.com/osrf/homebrew-simulation/pull/2203 to be merged first

homebrew CI build is fixed

2023-02-15 08:37 UTC, ahcorde approved these changes

2023-02-15 17:26 UTC, merged