Split ServerConfig and ClientConfig across multiple files
gazebosim/gz-fuel-tools pull request #380
Opened 2023-09-27 15:13 UTC by mjcarroll

A single header was containing both classes, this just splits those up.

2023-09-27 15:21 UTC, ahcorde requested changes

2023-09-27 15:21 UTC, ahcorde commented on include/gz/fuel_tools/ServerConfig.hh
> +#include <vector>
where is vector used?

2023-09-27 15:21 UTC, ahcorde commented on src/ServerConfig.cc
> +#include <vector>
where is vector used?

2023-09-27 15:21 UTC, ahcorde commented on src/ServerConfig_TEST.cc
> +
```suggestion
}

```

2023-10-04 15:13 UTC, mjcarroll commented on include/gz/fuel_tools/ServerConfig.hh
> +#include <vector>
removed

2023-10-04 15:13 UTC, mjcarroll commented on src/ServerConfig.cc
> +#include <vector>
removed

2023-10-13 07:37 UTC, ahcorde approved these changes

2023-10-13 15:11 UTC, mjcarroll commented
Windows failures will be addressed with forward ports of #376

2023-10-13 15:11 UTC, merged