CLI for creating config.yaml
gazebosim/gz-fuel-tools pull request #413
Opened 2024-04-09 23:59 UTC by nkoenig

# 🎉 New feature

## Summary

This simplifies the process of creating a config.yaml file by supporting the `gz fuel configure` CLI. This new CLI walks a user through the process of creating a config.yaml file that will live in `~/.gz/fuel/`. 

The primary benefit is that it makes it easier to store and then use private access tokens.

## Test it

1. Run the full guided process with:
```
gz fuel configure
```
2. Accept the defaults, and create a standard config file.
```
gz fuel configure --defaults
```
3. Accept the defaults, and output the result to the console.
```
gz fuel configure --defaults --console
```

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [x] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-04-10 08:23 UTC, ahcorde requested changes

2024-04-10 08:23 UTC, ahcorde commented on README.md
> +```
```suggestion
```bash
```

2024-04-10 08:23 UTC, ahcorde commented on README.md
> +
```suggestion
```

2024-04-10 08:23 UTC, ahcorde commented on README.md
> +```
```suggestion
```bash
```

2024-04-10 08:23 UTC, ahcorde commented on tutorials/02_configuration.md
> +```
```suggestion
```bash
```

2024-04-10 21:28 UTC, nkoenig commented on tutorials/02_configuration.md
> +```
[98719eb](https://github.com/gazebosim/gz-fuel-tools/pull/413/commits/98719eb12f242df49e9cfa2998ce19673db3ad05)

2024-04-10 21:28 UTC, nkoenig commented on README.md
> +```
[98719eb](https://github.com/gazebosim/gz-fuel-tools/pull/413/commits/98719eb12f242df49e9cfa2998ce19673db3ad05)

2024-04-10 21:28 UTC, nkoenig commented on README.md
> +```
[98719eb](https://github.com/gazebosim/gz-fuel-tools/pull/413/commits/98719eb12f242df49e9cfa2998ce19673db3ad05)

2024-04-25 12:58 UTC, ahcorde approved these changes

2024-04-25 12:58 UTC, merged