9 :arrow_right: main
gazebosim/gz-fuel-tools pull request #423
Opened 2024-05-30 15:12 UTC by Crola1702

# ➡️ Forward port

Port 9 to main

Branch comparison: https://github.com/gazebosim/gz-fuel-tools/compare/main...9

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

2024-05-30 21:54 UTC, azeey approved these changes

2024-05-30 21:56 UTC, azeey commented
I can't merge because GitHub says "This branch cannot be rebased due to conflicts". Can you merge from `main` locally and push?

2024-05-31 19:29 UTC, Crola1702 commented
I don't see any new changes from main, so I don't have anything else to push here :thinking:

2024-05-31 21:05 UTC, azeey requested changes
I actually found a couple of issues. Maybe making those changes and pushing will fix the GitHub issue?

2024-06-06 14:01 UTC, Blast545 commented on package.xml
> +  <name>gz-fuel_tools9</name>
Addressed on: c991fc2

2024-06-06 14:01 UTC, Blast545 commented on package.xml
> +  <depend>gz-utils2</depend>
Addressed on: c991fc2

2024-06-06 21:50 UTC, azeey approved these changes

2024-06-06 21:51 UTC, merged